### ISSUE TITLE
ENHANCEMENT: Image Editing Re-Upload To Server

### ISSUE THREAD

**Issue by marcelgruber** [klogue214/tinyMCE-image-upload-plugin-for-laravel#1]
Hey Friend,

So, using imagetools, you can modify the image, but then it is stored as a blob within the text editor and no longer as an external resource. Can we work together to try to setup re-upload / edit on the server side after modifications are made to the image?

**Comment by klogue214** [comment]
I'm not quite sure what you're trying to do.

**Comment by marcelgruber** [comment]
Okay, try enabling the 'imagetools' plugin. Notice how you can modify an image that was uploaded using this code. Only problem is that now the edited image is stored as a blob and it is no longer technically the uploaded file. That edited image needs to be reuploaded to the server in order to persist the changes.

Know what I mean?

I have an outstanding question on Github for this:

http://stackoverflow.com/questions/32599125/tinymce-4-imagetools-not-working-for-remotely-stored-images

**Comment by klogue214** [comment]
Honestly, I can't help you on that issue.  It seems to be changing the core functionality of the imagetools plugin.  This is not really related to the objective of the plugin I wrote here, so I'm going to close the issue.  Good luck in seeking out a solution.  I'm of no help when it comes to decoding the core packages and don't intend to venture down that path.

**Comment by marcelgruber** [comment]
It's not editing the imagetools plugin at all :)

Here is why:

**Comment by marcelgruber** [comment]
It's not editing the imagetools plugin at all :)

Here is why:
http://www.tinymce.com/wiki.php/Handling_Asynchronous_Image_Uploads
http://www.tinymce.com/wiki.php/PHP_Upload_Handler

The TLDR of those pages is that, out of the box, TinyMCE 4 supports asynchronous image uploads. Adding such functionality to the source and documentation of this repo is a natural extension of its initial goal. So, using this repo code, the user can upload an image into the editor, and the image is stored somewhere remotely. BUT now, what if the user wants to edit the image, or even just resize it? Then the image will be changed into a blob, and the edits will not persist onto the server unless it is re-uploaded asynchronously. See what I mean? 

TinyMCE provides the tools by which we can add this functionality. It's just a matter of us adding and changing a bit of code. For example, changing the 'file_path' return paramater name to 'location' will already get us one step closer to being able to have this functionality. Other than that, adding an event handler to the plugin, and then possibly some server side code to handle this uploaded blob, and suddenly you have a complete solution to the whole problem. I hope you see what I mean.
